[package]
name = "pingworker"
version = "0.1.0"
authors = ["Roshan <rpawar@fispan.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
url = "2.1.1"